### PR TITLE
add sortingcomponents overview tutorial

### PR DESCRIPTION
**Pull request by pauladkisson**
New SortingComponents Tutorial uses updated signatures and a Neuropixels data example of the following modules:
- Peak Detection
- Peak Localization
- Peak Selection
- Clustering
- Template Matching

### CODE REVIEW

**Comment by pauladkisson** [comment]
@alejoe91 @samuelgarcia whenever you get a chance, please review.

**Comment by alejoe91** [comment]
Thanks @pauladkisson 

This looks awesome!!! great work :)

A couple of small comments:

- the ignore filters doesn't seem to do its job. Can you double check that? Sometimes re-running the cell makes the trick. 
- the print markdown also doesn't render when I open the notebook locally, so I suspect it might also not render correctly in the automatically generated rst file
- clustering: when plotting the waveforms, it would be nice to use more then one channel per unit (maybe a radius of 30/40 um). Optionally, all waveforms/templates could also be displayed on the same axis!
- In the `Putting it all together`, instead of making a function, do you think it would be possible (and useful) to create a SpikeInterface-based sorter from the `BaseSorter` class? (similar to SC2 and TDC2). Then the function could just be a wrapper to the class methods.

**Comment by pauladkisson** [comment]
Hey @alejoe91,
I put together an alternate implementation of the '**Putting it all together**' section with a class that inherits from ``BaseSorter``, but I feel like it adds unnecessary complexity for no real reason.
- I have to rewrite the `initialize_folder` method to avoid the 'NotInstalled' error, which introduces a lot of extra code for the reader to parse through
- The user-defined sorter doesn't even work with `spikeinterface.sorters.run_sorter()`, so it's unclear why we even go to the trouble of defining a class with this particular structure.

For comparison, here is the code block for the function-based pipeline:
```
def cluster2waveform(recording, peaks, labels, path, job_kwargs=None): 
    '''Combines recording, peaks, and labels and repackages them into a waveform extractor
           with specified path'''
    if job_kwargs is None:
        job_kwargs = {}
    if not path.exists():
        path.mkdir()
        
    sorting = se.NumpySorting.from_times_labels(peaks['sample_ind'], labels, recording.sampling_frequency)
    sortpath = path / "sorting.npz"
    se.NpzSortingExtractor.write_sorting(sorting, sortpath)
    sorting_extractor = se.NpzSortingExtractor(sortpath)
    wavepath = path / "waveforms"
    we = sc.extract_waveforms(recording, sorting_extractor, wavepath,
                              ms_before=1.5, ms_after=2, overwrite=True, **job_kwargs)
    return we

def my_spikesorter(recording, path):
    # Setup
    job_kwargs = dict(n_jobs=4, chunk_duration="1s", progress_bar=True)
    recpath = path / "recording"
    if not recpath.exists():
        recording.save(folder=recpath, **job_kwargs)
    rec_pproc = sc.load_extractor(recpath)
    
    # Peak Detection
    print("...Detecting Peaks...")
    noise_levels = sc.get_noise_levels(recording, return_scaled=False)
    detect_kwargs = dict(peak_sign='neg', detect_threshold=5, exclude_sweep_ms=0.2, noise_levels=noise_levels)
    peaks = detect_peaks(recording, method='locally_exclusive', local_radius_um=50,
                             **detect_kwargs, **job_kwargs)
    
    # Peak Localization
    print("...Localizing Peaks...")
    localize_kwargs = dict(local_radius_um=150, ms_before=0.3, ms_after=0.6)
    peaklocs = localize_peaks(recording, peaks, method='monopolar_triangulation',
                                  **localize_kwargs, **job_kwargs)
    
    # Peak Selection
    print("...Selecting Peaks...")
    select_kwargs = dict(n_peaks = 10_000, noise_levels=noise_levels, by_channel=False)
    peaks = select_peaks(peaks, method='smart_sampling_locations',
                         peaks_locations=peaklocs, **select_kwargs)
    peaklocs = localize_peaks(recording, peaks, method='monopolar_triangulation',
                                  **localize_kwargs, **job_kwargs)
    
    # Clustering
    print("...Clustering...") 
    _, labels = find_cluster_from_peaks(recording, peaks, method_kwargs=dict(peak_locations=peaklocs), 
                                        method="sliding_hdbscan", **job_kwargs)
    
    # Curating
    print("...Curating...")
    true_peaks = peaks[labels>=0]
    true_labels = labels[labels>=0] # omit noise clusters
    we = cluster2waveform(recording, true_peaks, true_labels, path, job_kwargs=job_kwargs)
    
    # Tempate Matching
    print("...Template Matching...")
    method_kwargs = dict(waveform_extractor=we, noise_levels=noise_levels, num_closest=3)
    spikes = find_spikes_from_templates(rec_pproc, method='tridesclous', method_kwargs=method_kwargs)
    labels = spikes['cluster_ind']
    final_path = path / "final"
    we = cluster2waveform(recording, spikes, labels, final_path, job_kwargs=job_kwargs)
    return we
```

And here is the code block defining the BaseSorter-based pipeline:
```
import shutil
class MySorter(BaseSorter):
    _default_params = {
        'job_kwargs' : dict(n_jobs=4, chunk_duration="1s", progress_bar=True),
        
        'detect_method' : 'locally_exclusive',
        'detect_kwargs' : dict(peak_sign='neg', detect_threshold=5, 
                               exclude_sweep_ms=0.2, local_radius_um=50),
        
        'localize_method' : 'monopolar_triangulation',
        'localize_kwargs' : dict(local_radius_um=150, ms_before=0.3, ms_after=0.6),
        
        'select_method' : 'smart_sampling_locations',
        'select_kwargs' : dict(n_peaks = 10_000, by_channel=False),
        
        'cluster_method' : 'sliding_hdbscan',
        'cluster_kwargs' : {},
        
        'tmatch_method' : 'tridesclous',
        'tmatch_kwargs' : dict(num_closest=3)
    }
    
    
    def __init__(self, recording, output_folder, params=None, **kwargs):
        super().__init__(recording=recording, output_folder=output_folder, remove_existing_folder=True)
        self.params = self._default_params.copy()
        if params is not None:
            for k, v in params.items():
                self.params[k] = v
    
    def __call__(self, verbose=True):
        return self._run_from_folder(self.recording, self.sorter_folder, self.params, verbose)
    
    @classmethod
    def initialize_folder(cls, recording, output_folder, verbose, remove_existing_folder):
        if cls.requires_locations:
            locations = recording.get_channel_locations()
            if locations is None:
                raise RuntimeError("Channel locations are required for this spike sorter. "
                                   "Locations can be added to the RecordingExtractor by loading a probe file "
                                   "(.prb or .csv) or by setting them manually.")

        if output_folder is None:
            output_folder = cls.sorter_name + '_output'

        #  .absolute() not anymore
        output_folder = Path(output_folder)
        sorter_output_folder = output_folder / "sorter_output"

        if output_folder.is_dir():
            if remove_existing_folder:
                shutil.rmtree(str(output_folder))
            else:
                raise ValueError(f'Folder {output_folder} already exists')

        output_folder.mkdir(parents=True, exist_ok=True)
        sorter_output_folder.mkdir()

        if recording.get_num_segments() > 1:
            if not cls.handle_multi_segment:
                raise ValueError(
                    f'This sorter {cls.sorter_name} do not handle multi segment, use si.concatenate_recordings(...)')

        rec_file = output_folder / 'spikeinterface_recording.json'
        if recording.is_dumpable:
            recording.dump_to_json(rec_file)
        else:
            d = {'warning': 'The recording is not dumpable'}
            rec_file.write_text(json.dumps(d, indent=4), encoding='utf8')

        return output_folder
    @classmethod
    def cluster2waveform(cls, recording, peaks, labels, path, job_kwargs=None): 
        '''Combines recording, peaks, and labels and repackages them into a waveform extractor
               with specified path'''
        if job_kwargs is None:
            job_kwargs = {}
        if not path.exists():
            path.mkdir()

        sorting = se.NumpySorting.from_times_labels(peaks['sample_ind'], labels, recording.sampling_frequency)
        sortpath = path / "sorting.npz"
        se.NpzSortingExtractor.write_sorting(sorting, sortpath)
        sorting_extractor = se.NpzSortingExtractor(sortpath)
        wavepath = path / "waveforms"
        we = sc.extract_waveforms(recording, sorting_extractor, wavepath,
                                  ms_before=1.5, ms_after=2, overwrite=True, **job_kwargs)
        return we
    
    @classmethod
    def _run_from_folder(cls, recording, sorter_output_folder, params, verbose):
        # Noise Levels
        if verbose:
            print("...Acquiring Noise Levels...")
        if 'noise_levels' in params.keys():
            noise_levels = params['noise_levels']
        else:
            noise_levels = sc.get_noise_levels(recording, return_scaled=False)
        
        # Peak Detection
        if verbose:
            print("...Detecting Peaks...")
        job_kwargs = params['job_kwargs']
        detect_kwargs = params['detect_kwargs']
        detect_method = params['detect_method']
        peaks = detect_peaks(recording, method=detect_method, noise_levels=noise_levels,
                             **detect_kwargs, **job_kwargs)

        # Peak Localization
        if verbose:
            print("...Localizing Peaks...")
        localize_kwargs = params['localize_kwargs']
        localize_method = params['localize_method']
        peaklocs = localize_peaks(recording, peaks, method=localize_method,
                                      **localize_kwargs, **job_kwargs)

        # Peak Selection
        if verbose:
            print("...Selecting Peaks...")
        select_kwargs = params['select_kwargs']
        select_method = params['select_method']
        peaks = select_peaks(peaks, method=select_method,
                             peaks_locations=peaklocs, **select_kwargs)
        peaklocs = localize_peaks(recording, peaks, method=select_method,
                                      **localize_kwargs, **job_kwargs)

        # Clustering
        if verbose:
            print("...Clustering...") 
        cluster_method = params['cluster_method']
        cluster_kwargs = params['cluster_kwargs']
        cluster_kwargs['peak_locations'] = peaklocs
        _, labels = find_cluster_from_peaks(recording, peaks, method=cluster_method,
                                            method_kwargs=cluster_kwargs, **job_kwargs)

        # Curating
        if verbose:
            print("...Curating...")
        true_peaks = peaks[labels>=0]
        true_labels = labels[labels>=0] # omit noise clusters
        we = cluster2waveform(recording, true_peaks, true_labels, sorter_output_folder, job_kwargs=job_kwargs)

        # Tempate Matching
        if verbose:
            print("...Template Matching...")
        tmatch_method = params['tmatch_method']
        tmatch_kwargs = params['tmatch_kwargs']
        tmatch_kwargs['waveform_extractor'] = we
        tmatch_kwargs['noise_levels'] = noise_levels
        spikes = find_spikes_from_templates(recording, method=tmatch_method, method_kwargs=tmatch_kwargs)
        labels = spikes['cluster_ind']
        final_path = sorter_output_folder / "final"
        we = cluster2waveform(recording, spikes, labels, final_path, job_kwargs=job_kwargs)
        return we
```

**Comment by alejoe91** [comment]
Thanks @pauladkisson 

Indeed, I think you're right...at this point we can probably avoid the additional complexity! 

After talking to @samuelgarcia, we think that we should keep this open and keep adding to this with new methods and benchmarks as we develop them. 

This way, once the first part of the project (i.e., extending the components) is complete, this will reflect what is there (and maybe we could also add additional plots and benchmarks). Is that ok for you?

**Comment by pauladkisson** [comment]
Hey @alejoe91, 

I would prefer to go ahead and close it now (+revisions if necessary), and make a new one whenever we release v0.98.0.

Right now it explicitly runs from v0.97.0, so any user who installs that version of spikeinterface can run the notebook with the same output.  If we link it to the source, we lose that consistency.  It will also be a bit annoying to constantly update as signatures change.  Plus, it's already pretty long, so tbh I would prefer a second 'advanced' sorting components tutorial to flesh out additional features/functionality (ex. motion estimation/correction).

I would be happy to write up an up-to-date (v0.97.0) 'advanced' sorting components tutorial to complement this one, although right now I'm itching to start implementing stuff (ex. template deconvolution).  Maybe I can keep it on my to-do list to take care of sometime down the line?

**Comment by pauladkisson** [comment]
Also, I wanted to mention that I did not add neighboring channels to the waveform plots.  It really becomes very difficult to appreciate any details in the waveforms once a few neighboring channels are added.  Since you can already localize the spikes with the location plots on the probe, I think it's appropriate to focus on the principal channel waveforms for waveform visualization.

**Comment by pauladkisson** [comment]
Hey @alejoe91,

I was looking at [SpikeInterface Reports](https://spikeinterface.github.io/), and I noticed the new notebook still isn't on there.  I tried to execute ``>>> nikola github_deploy`` myself, but I get a 403 permissions error.  Would you mind either giving me permission to deploy the new site or doing it yourself?

Thanks

**Comment by samuelgarcia** [comment]
Hi Paul.
I will do it.

**Pull request merged**
